# Generated by Django 4.2.16 on 2026-09-30 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Engineering, Operations)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe unique identifier', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional category description')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_identifier', models.CharField(db_index=True, help_text='User ID, API key, or IP address triggering pipeline execution', max_length=255)),
                ('endpoint', models.CharField(default='/api/tasks/pipeline/execute/', help_text='API endpoint evaluated for rate limiting', max_length=255)),
                ('requests_count', models.PositiveIntegerField(default=1, help_text='Number of requests recorded in the current sliding window')),
                ('window_limit', models.PositiveIntegerField(default=60, help_text='Maximum allowed requests in the sliding time window')),
                ('is_throttled', models.BooleanField(default=False, help_text='True if request exceeded quota and was rejected (HTTP 429)')),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Start timestamp of the current rate limit evaluation window')),
                ('reset_at', models.DateTimeField(help_text='Timestamp when client quota will be fully replenished')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short descriptive title of the task', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed task specification and context')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current lifecycle state', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', help_text='Relative urgency and impact level', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', help_text='Email or handle of the assignee', max_length=150)),
                ('due_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when status transitioned to COMPLETED', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetryPolicyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='execute_pipeline', help_text='Action being executed under retry protection', max_length=100)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Current attempt counter (1 to max_attempts)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Configured maximum retry attempts before dead-letter routing')),
                ('backoff_delay_ms', models.PositiveIntegerField(default=0, help_text='Calculated backoff delay in milliseconds for this attempt')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('RETRYING', 'Retrying'), ('DEAD_LETTER', 'Dead Letter Routed'), ('CIRCUIT_OPEN', 'Circuit Breaker Open')], default='SUCCESS', help_text='Outcome of the retry step', max_length=30)),
                ('error_message', models.TextField(blank=True, default='', help_text='Diagnostic failure details if attempt failed')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(blank=True, help_text='Task subject to retry execution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retry_logs', to='tasks.task')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['client_identifier', 'created_at'], name='tasks_ratel_client__539f40_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='tasks_task_status_02f831_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='tasks_task_assigne_1f513a_idx'),
        ),
        migrations.AddIndex(
            model_name='retrypolicylog',
            index=models.Index(fields=['task', 'attempt_number'], name='tasks_retry_task_id_8df121_idx'),
        ),
        migrations.AddIndex(
            model_name='retrypolicylog',
            index=models.Index(fields=['status'], name='tasks_retry_status_811e74_idx'),
        ),
    ]
