# Generated by Django 4.2 on 2026-09-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category display name', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the category')),
                ('color_hex', models.CharField(default='#3B82F6', help_text='Hex color code for UI badges', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief summary of the task', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed task specification')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='TODO', help_text='Current task lifecycle status', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Urgency and impact priority', max_length=20)),
                ('assignee_email', models.EmailField(blank=True, default='', help_text='Primary assignee notification recipient', max_length=254)),
                ('due_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when task was marked as DONE', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Destination email or webhook URL', max_length=255)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook'), ('IN_APP', 'In-App Notification')], default='EMAIL', help_text='Notification medium', max_length=20)),
                ('subject', models.CharField(help_text='Notification subject headline', max_length=255)),
                ('message', models.TextField(help_text='Notification body content')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', help_text='Delivery transmission status', max_length=20)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict, help_text='JSON payload dispatched to endpoint')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error reason if transmission failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Related task instance', on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='system', help_text='User, worker, or service identifier triggering the action', max_length=150)),
                ('action', models.CharField(choices=[('STATUS_TRANSITION', 'Status Transition'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DELETED', 'Task Deleted')], default='STATUS_TRANSITION', help_text='Classification of event', max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, default='127.0.0.1', help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, default='internal-service/1.0', help_text='Client User-Agent header', max_length=255)),
                ('checksum', models.CharField(blank=True, help_text='Cryptographic SHA-256 integrity checksum', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contextual details of the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Related task instance', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_5bca9d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='tasks_task_priorit_a8d462_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_task_due_dat_063853_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['task', 'channel'], name='tasks_notif_task_id_81df42_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='tasks_notif_status_27d79b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['task', 'action'], name='tasks_audit_task_id_6336be_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='tasks_audit_actor_211245_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='tasks_audit_created_882875_idx'),
        ),
    ]
